### ISSUE TITLE
cannot mock the final protected function getRepository()

### ISSUE THREAD

**Issue by phucwan91** [sonata-project/sonata-doctrine-extensions#142]
Hi

I want to write unit test for a method in my manager that extends the `BaseEntityManager`
I use `getRepository` to make a query then I have some business logic for a result which is get from the query, before the result is returned.

I just want to test my business logic so I mock the `getRepository()` (because the returned result from the query does not matter for me in that case)
But the php unit is not able to do that because of the `final` modifier

Can we remove the that `final` modifier ?

**Comment by core23** [comment]
The method was introduces with https://github.com/sonata-project/sonata-doctrine-extensions/pull/134.

You could just remove the `getRepository` method from your class and everything should work

**Comment by phucwan91** [comment]
sorry if I misunderstood ! I still need the `getRepository()` in my class, what's a alternative method if I remove the `getRepository()` ?

**Comment by core23** [comment]
You cou provide a PR with a fix, that removes the `final` modifier @phucwan91 

https://github.com/sonata-project/sonata-doctrine-extensions/pull/134#issuecomment-516117894 cc @greg0ire :trollface:
