### ISSUE TITLE
Add support for doctrine/persistence 3

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/sonata-doctrine-extensions#407]
## Feature Request

Currently blocked by
```          
doctrine/mongodb-odm                2.3.3    requires  doctrine/persistence (^2.2)          
doctrine/phpcr-odm                  1.6.0    requires  doctrine/persistence (^1.3.7 || ^2.0)          
symfony/doctrine-bridge             v6.0.7   requires  doctrine/persistence (^2)  
```

For mongodb-odm, it will be in the 2.4.0 https://github.com/doctrine/mongodb-odm/issues/2419
For symfony too: https://github.com/symfony/doctrine-bridge/blob/5.4/composer.json#L21
But I don't know if https://github.com/doctrine/phpcr-odm will support persistence 3 ; there is not a lot of activity.

@jordisala1991, should we
1) Deprecate the phpcr-odm support
2) Remove the phpcr-odm dependency from require-dev
3) Defining it as a variant https://github.com/sonata-project/dev-kit/blob/master/config/projects.yaml#L38

Or do you see another solution ?

**Comment by jordisala1991** [comment]
Yes, we should deprecate phpcr from here too.
