### ISSUE TITLE
Implements TransactionalManagerInterface

### ISSUE THREAD

**Issue by eerison** [sonata-project/sonata-doctrine-extensions#442]
## Implements TransactionalManagerInterface and Use in SnapshotManagerInterface

This idea was raised in this PR: sonata-project/SonataPageBundle#1548

- Create test for Create and cleanup snapshots, to make sure that `beginTransaction` and `commit` methods are called

**Comment by eerison** [comment]
Ok we have the first problem here, sonata-doctrine-extension requires php 8

https://github.com/sonata-project/sonata-doctrine-extensions/blob/2.x/composer.json

But in my option we should release 4.0 with support for `7.4` what do you think?

**Comment by eerison** [comment]
@VincentLanglet

**Comment by VincentLanglet** [comment]
> Ok we have the first problem here, sonata-doctrine-extension requires php 8
> 
> https://github.com/sonata-project/sonata-doctrine-extensions/blob/2.x/composer.json
> 
> But in my option we should release 4.0 with support for `7.4` what do you think?

It's not a problem. We can still introduce the feature for now.
And we'll use it on PageBundle when the support for php 7.4/doctrine-extensions 2 will be dropped.

**Comment by eerison** [comment]
> > Ok we have the first problem here, sonata-doctrine-extension requires php 8
> > https://github.com/sonata-project/sonata-doctrine-extensions/blob/2.x/composer.json
> > But in my option we should release 4.0 with support for `7.4` what do you think?
> 
> It's not a problem. We can still introduce the feature for now. And we'll use it on PageBundle when the support for php 7.4/doctrine-extensions 2 will be dropped.

Ok I got it ;)

**Comment by jordisala1991** [comment]
IMO this issue should be moved to doctrine extensions

**Comment by eerison** [comment]
I would say it's done
