### ISSUE TITLE
Developers don't let developers use dev-master in composer. Please tag releases regularly

### ISSUE THREAD

**Issue by SchizoDuckie** [sonata-project/sonata-doctrine-extensions#9]
I'm currently evaluating the usage of Sonata bundles in our projects, and this was one of tiny little things that stood out in a negative way to me.

Please:
- Tag the recent commits in some semantic versioning compatible way
- update the readme to refer to ~1.0 instead of dev-master

**Comment by Soullivaneuh** [comment]
You already have a stable version. The actual last one: https://github.com/sonata-project/sonata-doctrine-extensions/releases/tag/1.0.2

I'll update the documentation.

**Comment by SchizoDuckie** [comment]
Excellent thanks :+1:
